from . import product_template
from . import ecommerce_channel
from . import product_bulk_pricing_rule
from . import custom_field_line
from . import product_channel
from . import product_channel_variant
from . import product_channel_category
from . import product_pricelist
from . import channel_pricelist
from . import customer_channel
from . import sale_order
from . import tax_class
from . import stock_picking
from . import product_brand
from . import order_status_channel
from . import product_imported_field
from . import product_exported_field
from . import channel_data_type
from . import resource_import_operation_type
from . import customer_group
from . import account_tax
